### ISSUE TITLE
Plugin always returns the previous value of a field for a NULL value in query

### ISSUE THREAD

**Issue by arpanm96** [grafana/redshift-datasource#110]
**Plugin always fills missing values with the previous value instead of the option configured in Grafana Query Editor**:

**What you expected to happen**:
When "Fill Value" is configured to NULL, the fields having NULL values should return NULL.

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure Fill Value as NULL in Query Editor
2. Fire a query returning NULL values in the raw query
3. Check the data retrieved by the redshift data source plugin 

**Screenshots**

Fill Value configured to NULL
![image](https://user-images.githubusercontent.com/17992485/149294212-63ceeffa-3412-425f-8d89-88c7b2b29721.png)

Actual Redshift query executed in Redshift query editor in AWS
![image](https://user-images.githubusercontent.com/17992485/149293035-119917e2-4650-4efa-aa98-802eafcb7b03.png)

In grafana redshift query inspector, 
![image](https://user-images.githubusercontent.com/17992485/149293166-ddf6d959-79ed-4a87-ae6b-f17f0d854af1.png)

**Anything else we need to know?**:
We have looked into the codebases of sqlds, grafana-sdk-plugin-go, athena and clickhouse datasources, the fillmode seems to be set and used correctly, so not sure what the issue is. The only distinct thing that we found was clickhouse datasource configures the fillmode using the Fillmode() method and not the Settings(), as is there in the sqlds driver.

**Environment**:
- Grafana version: 8.3.0
- Plugin version: 1.0.1
- OS Grafana is installed on: Linux
- User OS & Browser: Tested on Safari & Chrome
- Others:

**Comment by andresmgot** [comment]
I am able to reproduce the issue, will investigate and let you know. Thanks for reporting!

**Comment by andresmgot** [comment]
There are two different issues here:

 - The Fill Value input only applies when the frames are formatted as Time Series. This is used to fill frames in the Time Series panel. We should not show it for table frames since it's indeed confusing.
 - Null values should be returned as `null` not the previous value (this is the behavior of the PostgreSQL data source, for example).

#112 fixes this
