### ISSUE TITLE
One Minute Timeout Too Short 

### ISSUE THREAD

**Issue by brucetly** [grafana/redshift-datasource#167]
**What happened**:
Dashboards using 7 day queries are mainly timing out due to 1 minute timeout without any way to change the timeout to something larger than 1 minute.

**What you expected to happen**:
Timeout should be larger than 1 minute (5 minutes is ok). Prefer it to be configurable.

**How to reproduce it (as minimally and precisely as possible)**:
Any chart query that will normally run longer than 1 minute will consistently timeout.

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.4.7
- Plugin version: Unknown
- OS Grafana is installed on: AWS Managed Grafana
- User OS & Browser: Mac & Edge browser 
- Others:

**Comment by iwysiu** [comment]
Hi @brucetly , thanks for filing this issue! We're currently looking into better handling for long running queries (see the discussion [here](https://github.com/grafana/grafana/discussions/45325))

**Comment by sarahzinger** [comment]
@brucetly we recently (as of 1.4.0) introduced a new way of handling long running queries which I believe should be available for testing with a feature toggle: https://github.com/grafana/redshift-datasource#async-query-data-support going to close this ticket as I believe it should solve your issue, but if it does not let us know and we can reopen the ticket!
