### ISSUE TITLE
Random query errors using the latest version

### ISSUE THREAD

**Issue by stefano-cherchi** [grafana/redshift-datasource#182]
**What happened**: 
EDIT: upon further investigation, the plugin version seems to have no role in the issue. This is the correct scenario.

We've been using a redshift data source (configured using version 1.0.5 of the official RedShift plugin) for months to feed data to dozens of dashboards on Grafana 9.0.5. It all worked flawlessly until last week. This Monday we started seeing some strange behaviour: all the panels using the redshift data source started returning random errors. No changes had been made anywhere in the deployment during the weekend.  This is the same dashboard before and after a page refresh:

before:

![image](https://user-images.githubusercontent.com/3993552/192518547-741b3902-c2c2-4231-9a27-0400be3535b7.png)

after refreshing the page:

![image](https://user-images.githubusercontent.com/3993552/192518892-382eb723-5d2d-4f9c-97ff-a1a25177c0be.png)

after opening the Inspect -> Query panel and clicking on "Refresh"

![image](https://user-images.githubusercontent.com/3993552/192524655-563b79ee-7b5a-4e1c-96bc-56cbb19421fd.png)

The query inspector always returns this error:

![image](https://user-images.githubusercontent.com/3993552/192519361-858c464b-0415-4751-8652-32555ec5f83a.png)

Some times, clicking on the "Refresh" button fixes the issue, some times it doesn't. 

The behaviour seems to be totally random. 

The same queries return the expected data if run directly against the Redshift database using a local client or the AWS console query editor with the same credentials.

We have updated both Grafana to version 9.1.6 and the plugin to version 1.2.0, to no avail.

Replacing the data source with one that uses the PostgreSQL plugin solves the issue 100% of the times.

**What you expected to happen**:

I expect all the panels to load consistently with no errors as before the plugin upgrade.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open any panel using a redshift data source
2. See the message "Query error: 500 Internal Server Error"
3. Refresh the page or open the Inspect panel and click on Query -> Refresh
4. The error might or might not disappear, randomly (mostly, it doesn't)

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.5 and then 9.1.6
- Plugin version: 1.0.5 and then 1.2.0
- OS Grafana is installed on: Debian 5.10.140-1
- User OS & Browser: MacOS with latest versions of both Chrome and Firefox, Windows with latest version of Chrome
- Others:

**Comment by fridgepoet** [comment]
Hi, what plugin version did you upgrade from?

**Comment by sunker** [comment]
We've closed this issue since it needs more information and hasn't had any activity recently. We can re-open it after you you add more information. To avoid having your issue closed in the future, please read our [CONTRIBUTING](https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md) guidelines.
