### ISSUE TITLE
Use getDefaultQuery method to set default query

### ISSUE THREAD

**Issue by sunker** [grafana/redshift-datasource#191]
Instead of calling onChange to set default query for new queries, we should use the new [getDefaultQuery](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/datasource.ts#L360) method defined in the data source api. We can use the same default query as today. https://github.com/grafana/redshift-datasource/blob/bbfb1e883e426cc85022c3581f3f7f9d22c05fb1/src/types.ts#L40-L44

Part of https://github.com/grafana/cloud-data-sources/issues/79

**Comment by idastambuk** [comment]
Closing as "won't do"
See https://github.com/grafana/oss-plugin-partnerships/issues/79#issuecomment-1549740717 for info
