### ISSUE TITLE
Time Series query error with Redshift 'REAL' data type

### ISSUE THREAD

**Issue by doanbutar** [grafana/redshift-datasource#204]
**What happened?**
When trying to create a Time Series visualization with a Redshift data source that has a column with data type `REAL`, the query fails with an `HTTP 500 - Internal Server Error`.

The same query is running on the same column with `int` data type works.

**What was expected to happen?**
Queries on REAL data type columns should also complete successfully.

**Steps to reproduce the problem:**
1. Create a redshift cluster with a column with `int` data type
2. Create a Time Series dashboard in Grafana
3. Run a time series query that selects this `int` data type column
4. Create additional column in redshift with `real` data type, and copy over int data to the `real` data type column
5. Modify time series query to use `real` datatype column instead
6. Query fails with "Internal Server Error" (see attached screenshot)

**Version numbers (grafana, prometheus, graphite, plugins, operating system, etc.):**
Grafana version: v8.4.7
Redshift version: v1.3.0
OS: Amazon Linux 2

**Configuration information:**
Redshift table schema is also attached as screenshot.

**Comment by doanbutar** [comment]
//Redshift Int type
![image](https://user-images.githubusercontent.com/38452094/214764982-08a17171-0625-47df-beb7-4f84cf3c8c02.png)

//Redshift listing table schema
![image](https://user-images.githubusercontent.com/38452094/214765045-d408ca85-8576-41db-840c-3fd5c7f24baa.png)

//Redshift real type
<img width="640" alt="Screenshot 2023-01-26 at 13 27 50" src="https://user-images.githubusercontent.com/38452094/214765107-6902ea26-63c2-4cd7-a17b-ac1e87e7a171.png">

**Comment by doanbutar** [comment]
Looking at this: https://github.com/grafana/redshift-datasource/pull/33
Inserting `real` datatype and also query seems to work fine.

**Comment by fridgepoet** [comment]
Thanks @doanbutar for the detailed bug report.

I was able to reproduce the issue by:
1. In AWS, create a redshift cluster
2. Create a table with a column type `real`: `create table foo(test real);`
3. Insert 1 value into the `real` column: `insert into foo(test) values (1.111111);`
4. In Grafana, create a time series panel and execute the query `select * from foo`

Result: error message `Query data error`

**Comment by grafpat** [comment]
Hi @fridgepoet , any update here? I see that this has been moved to Backlog, is there any update on rough timeline that this will be worked on?

**Comment by fridgepoet** [comment]
Hi @grafpat we don't have a firm timeline yet, will try to keep you informed when we pick this up.
