### ISSUE TITLE
Testing/Rollout for async query caching

### ISSUE THREAD

**Issue by iwysiu** [grafana/redshift-datasource#243]
What is the chore?:
Do Testing/Rollout for [async query caching](https://github.com/grafana/grafana/pull/71682).
instructions for testing and rollout: https://github.com/grafana/deployment_tools/tree/master/ksonnet/environments/hosted-grafana/waves/feature-toggles#instructions

Checklist for the steps in the link:

- [x]  Ensure cloud-readiness ([doc](https://docs.google.com/document/d/1H073k7QivcbHqeZJlKT1uMNs2BuIRUsQaydJ9tHpz58/edit#heading=h.nmhrirqphdnu))
- [x]  Test on single instance
- [x]  Roll out to dev and staging instances https://github.com/grafana/deployment_tools/pull/104514
- [x]  Roll out to canary https://github.com/grafana/deployment_tools/pull/107352
- [x]  Roll out to prod https://github.com/grafana/deployment_tools/pull/111807

**Comment by sarahzinger** [comment]
@iwysiu just wanted to make sure you saw https://github.com/grafana/redshift-datasource/issues/250 

I see this issue is marked as Next, are we currently in the middle of a rollout for async query caching in redshift? If we are does the above bug look related and should we pause it?

**Comment by iwysiu** [comment]
@sarahzinger I haven't started rolling it out yet, I was waiting until all the cw logs monaco stuff was wrapped up.

The linked issue is for just async queries (no caching). It makes sense to not start it while we wait on the async query bug to be fixed.

**Comment by iwysiu** [comment]
Waiting a week or two to roll out to prod after roll out to canary
