### ISSUE TITLE
Provisioning documentation shows wrong `type`

### ISSUE THREAD

**Issue by StephenKing** [grafana/redshift-datasource#244]
**What happened**:

I wanted to provision a Redshift data source. I followed the README and used:

```yaml
datasources:
  - name: redshift-data
    type: redshift
    ...
```
![Screenshot 2023-08-22 at 21 01 12](https://github.com/grafana/redshift-datasource/assets/277561/f7c3b6de-9538-4b34-9bd6-9076a606d925)
![Screenshot 2023-08-22 at 21 00 58](https://github.com/grafana/redshift-datasource/assets/277561/d4bf31d2-9c1b-4d92-9e2c-48ab24948d5f)

Whereas a new data source is provisioned, it's of an unknown type.

When I change to `type: grafana-redshift-datasource`, it's nicely provisioned and usable 👍 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Probably it doesn't matter, but we're adding the plugin via

```
GF_INSTALL_PLUGINS=....,grafana-redshift-datasource
```

**Environment**:
- Grafana version: 9.5.3
- Plugin version: 1.11.1
- OS Grafana is installed on: Linux

**Comment by StephenKing** [comment]
please let me know if I should file a PR to update the README.

**Comment by kevinwcyu** [comment]
Hi @StephenKing, thanks for the report.

> please let me know if I should file a PR to update the README.

Please feel free to open a PR.

> I assume this defines the data source type:
> 
> https://github.com/grafana/redshift-datasource/blob/be82734ac176927387d7e5da71523a6191fcea73/src/plugin.json#L5

Yes, that's correct.

**Comment by StephenKing** [comment]
sorry, took me a while to make that two-line change PR ;)
