### ISSUE TITLE
Upgrading to Grafana 10.1.1 causes all Redshift queries to timeout.

### ISSUE THREAD

**Issue by sasa-gojic** [grafana/redshift-datasource#250]
**What happened**:

Upgrading to Grafana 10.1.1 from 9.5.5 caused all of the previously working Redshift queries to timeout with 504 Gateway Timeout.

Subsequent downgrade to 10.0.3 restored the queries back to the working condition.

**What you expected to happen**:

Previously working Redshift queries to continue working with Grafana 10.1.1.

**How to reproduce it (as minimally and precisely as possible)**:

Generate a significant number of Redshift queries in a 24 hour period to degrade the response of ListStatements requests;

Background:
Aware that feature flag redshiftAsyncQueryDataSupport = true by default in Grafana 10.1.1 and applied the necessary policy updates.
DEV and UAT environments provided no indication of any Redshift timeout issues during the upgrade to 10.1.1.

Only when we deployed to our production environment where there is a significantly higher number of Redshift requests did we experience timeout issues.

Further investigation revealed redshift-data:ListStatements was being called in the async flow. 
Due to our high number of requests and Redshift's 24 hour query result retention, the number of statements in a 24 hour period can reach above 20,000.

This can cause the ListStatements request to take a long time to respond (up to 120 sec), long enough to timeout the Grafana data request.

Please let me know if more information is required.

**Screenshots**
![image](https://github.com/grafana/redshift-datasource/assets/64943245/87ed28a9-23bd-4d5a-9259-16b1cffa2da2)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 10.1.1
- Plugin version: 1.12.1

**Comment by thanissi** [comment]
We are experiencing the same issue after upgrading to 10.1.x. Can we get this resolved asap?

**Comment by iwysiu** [comment]
Hi! Sorry to hear that you're having problems, we've prioritized this issue to be worked on soon. Until we fix it, you can configure the `redshiftAsyncQueryDataSupport` to false ([docs for configuring feature toggles](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/) and it'll turn off the feature. If you're using Hosted Grafana, you can ask your support person to turn the toggle off for you.

**Comment by thanissi** [comment]
Hi @iwysiu thank you for the suggested workaround. We run our Grafana instance on AWS ECS and use environment variables to set any configurations. However, when we tried to set in ENV it didn't get picked up. I suspect it will only get picked up if RedshiftAsyncQueryDataSupport also exists in the default grafana.ini file.

Is there another way to disable this feature without having to modify or create default grafana.ini file?

**Comment by iwysiu** [comment]
Hi @thanissi ! I checked the documentation, and it looks like you if you have Grafana enterprise, you [can do runtime settings updates](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/settings-updates-at-runtime/) but otherwise, I think you'll have to update the grafana.ini file ([docs here](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/)). Sorry for the inconvenience!

**Comment by iwysiu** [comment]
Hi @thanissi and @sasa-gojic ! I've picked this up to work on, and I'm wondering:
1) Are you were using open source or enterprise grafana?
2) If you use enterprise, do you have query caching turned on?
The initial implementation of async queries didn't support grafana query caching and I'm trying to figure out if that's related.

**Comment by thanissi** [comment]
Hi @iwysiu we are using open source version so no access to the caching feature.

**Comment by iwysiu** [comment]
Hi @thanissi and @sasa-gojic ! I just released [v1.12.2](https://github.com/grafana/redshift-datasource/releases/tag/v1.12.2), which should fix this issue.

**Comment by thanissi** [comment]
Hi @iwysiu thank you so much for such a quick turn around. Will try it out.

**Comment by sasa-gojic** [comment]
Hi @iwysiu, thank you, will try it out and let you know the results :)
