### ISSUE TITLE
Add missing regions under Default Region

### ISSUE THREAD

**Issue by VermaPriyanka** [grafana/redshift-datasource#274]
**Is your feature request related to a problem? Please describe.**
3 AWS regions are missing in the Default Region drop-down on the Redshift data source page.

**Describe the solution you'd like**
Add regions: `il-central-1`, `ap-southeast-4 `and `ca-west-1` to the plugin, to be displayed under the Default region selector on data source configuration page. Would be nice, if regions list is automatically updated whenever the service is launched in new regions.

**Describe alternatives you've considered**
Tried adding these regions manually, but it gives the error: `InvalidClientTokenId: The security token included in the request is invalid status code: 403`

**Comment by iwysiu** [comment]
I hava a pr up to add the new regions, however, for the error you're seeing: Do you have the regions enabled on your account? I tried it and I get that error for optional regions that haven't been enabled, while if the region is enabled the query succeeds whether or not the option is added to the dropdown.
