### ISSUE TITLE
Add "cn-north-1" and "cn-northwest-1" to region selector

### ISSUE THREAD

**Issue by Vimao** [grafana/redshift-datasource#290]
**Is your feature request related to a problem? Please describe.**
No option to select CN AWS regions "cn-north-1" and "cn-northwest-1"

**Describe the solution you'd like**
Option to select "cn-north-1" and "cn-nortwest-1"

**Describe alternatives you've considered**
No alternatives available

**Additional context**
Currently plugin cannot query Redshift in CN AWS regions. This completely blocks functionality for monitoring data stored in Redshift on those regions

**Comment by njvrzm** [comment]
I've added this to our backlog to prioritize, thank you!

**Comment by idastambuk** [comment]
Hi @Vimao, we just released plugin v1.17.0 - can you upgrade and let us know if you can see cn-north-1" and "cn-northwest-1" now? Thanks!
