### ISSUE TITLE
Make it possible to change cluster, db and db user from within the query editor

### ISSUE THREAD

**Issue by sunker** [grafana/redshift-datasource#42]
The way the Redshift data source is currently setup, the cluster, database and database user is specified in the data source config page. If a user wants to test another cluster, they would have to setup a new data source. This is the standard way for configuring sql data sources in Grafana, and I think for any data base that use either ODBC or JDBC to connect to the db.  

During the Redshift demo, someone expressed a wish to be able to switch cluster, database and database user from within the query editor, without having to create a new data source. For us to be able to do that, we would need to make some changes to sqlds. I've created a [feature request issue](https://github.com/grafana/sqlds/issues/20) for that in the sqlds. In the redshift plugin, we'd need to change the connection interface in the driver and read the args that are passed to [QueryContext](https://github.com/grafana/redshift-datasource/blob/main/pkg/redshift/driver/connection.go#L31-L55). That way, the cluster, db and db user can be overridden on a per-query level. 

Please note that it's not confirmed that this is something we need to do - I just created the issue to in case it this would come up in a future meeting.

**Comment by katebrenner** [comment]
closing as wont do
